Fix compatibility to Python 3
StackStorm-Exchange/stackstorm-gitlab pull request #11
Opened 2021-03-08 11:02 UTC by cyberkov

Hello!

I just came across a problem in this pack, when running with the new StackStorm 3.4. This change fixed it for me.

Cheers Hannes

2021-03-08 13:05 UTC, nmaludy requested changes
@cyberkov Thanks for this fix! Can you please address these two final things:

- Add a Changelog entry here: https://github.com/StackStorm-Exchange/stackstorm-gitlab/blob/master/CHANGELOG.md
- Bump the `version` key in `pack.yaml` to `1.0.1`: https://github.com/StackStorm-Exchange/stackstorm-gitlab/blob/master/pack.yaml#L6

Thanks!

2021-03-09 13:22 UTC, cyberkov commented
Hi @nmaludy!

Thanks for the review. I bumped the version but kept the changelog message high level. I guess no one is really that interested in such small changes :-)

Best wishes
Hannes

2021-03-09 13:29 UTC, nmaludy approved these changes

2021-03-09 13:31 UTC, merged

2021-03-09 13:31 UTC, nmaludy commented
Thanks again for this fix! If you're interested in some StackStorm stickers via our Community Sticker Program , shoot me an email to nmaludy@gmail.com with your address and i'll get them sent over: https://github.com/StackStorm/discussions/wiki/Community-Sticker-Program